version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo === Installing reportgenerator tool ===
      - dotnet tool install -g dotnet-reportgenerator-globaltool
      - export PATH="$PATH:/root/.dotnet/tools"

  build:
    commands:
      - echo === Restoring dependencies ===
      - dotnet restore
      - echo === Building solution ===
      - dotnet build --no-restore
      - echo === Running unit tests ===
      - dotnet test Web.Tests/Web.Tests.csproj --logger "trx;LogFileName=test_results.trx"
      - echo === Generating HTML test report ===
      - reportgenerator "-reports:**/test_results.trx" "-targetdir:TestReport" -reporttypes:Html

artifacts:
  files:
    - TestReport/**/*  # Xuất HTML report
  discard-paths: no